In [2]:
from bs4 import BeautifulSoup
import requests
import re
import random
import pymongo
from pprint import pprint
myclient = pymongo.MongoClient("mongodb://localhost:27017/")

def clean(html_string):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', str(html_string)).strip()
    return cleantext

# url = 'https://www.amazon.in/OnePlus-Midnight-Black-256GB-Storage/product-reviews/B07DJCJBRD/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1'
# page = requests.get(url)
# soup = BeautifulSoup(page.text, 'html.parser')
# title = soup.find_all(attrs={"data-hook":"product-link"})
# imagelinks = soup.find_all(attrs={"class":"a-dynamic-image a-stretch-vertical"}) #doesnt work
# price = soup.find_all(attrs={"class":"a-color-price arp-price"})
# rating = soup.find_all(attrs={"data-hook":"rating-out-of-text"})
# print(clean(title).strip())
# print(clean(price).strip())
# print(clean(rating).strip())

# mydb = myclient["course5i"]
# mycol = mydb["oneplus 6t"]
# mydict = { "productTitle": clean(title).strip(), "Price": clean(price).strip(), "rating":clean(rating).strip() }

# x = mycol.insert_one(mydict)

/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


In [3]:
# battery life

battery_life_desc_list=[]
battery_life_sentiment_list=[]
rating=['positive','critical']
for rate in rating:
    print(rate)
    review_list=[]
    
    for i in range(1,4):
        reviews_url = 'https://www.amazon.in/OnePlus-Midnight-Black-128GB-Storage/product-reviews/B07DJHY82F/ref=cm_cr_arp_d_viewopt_kywd?ie=UTF8&reviewerType=all_reviews&sortBy=helpful&pageNumber='+str(i)+'&filterByStar='+rate+'&filterByKeyword=battery+life'
        page2 = requests.get(reviews_url)
        soup2 = BeautifulSoup(page2.text, 'html.parser')
        title = soup2.find_all(attrs={"data-hook":"review-title"})
        review = soup2.find_all(attrs={"class":"a-size-base review-text review-text-content"})
        for r in range(len(review)):
            desc=[]
            review_list.append(clean(title[r]))
            review_sentences = str(clean(review[r])).split('.')
            for sentence in review_sentences:
                if "battery" in sentence or "Battery" in sentence:
                    desc.append(sentence)
            battery_life_desc_list.append(desc)
        for i in range(len(battery_life_desc_list)):
            
            if(rate=="positive"):
                battery_life_sentiment_list.append([battery_life_desc_list[i],1])
            elif(rate=="critical"):
                battery_life_sentiment_list.append([battery_life_desc_list[i],0])
                
    for x in range(len(review_list)-2):
        print(battery_life_desc_list[x])

positive
["Pros:Great battery lifeAmazing performancePremium designImpressive rear and front cameraIn display fingerprint scanner is really fastCons:No headphone jack but you'll get a converterNo notification LEDNo microSD card slotI will give points on my personal experience of 2 days full usage as below:Weight: 9/10OS: 10/10Screen size: 10/10CPU: 10/10Performance: 10/10Storage: 10/10 (you'll get approx 113 gb for use)Battery: 8/10Rear camera: 10/10Front camera: 10/10In display fingerprint scanner: 9/10Face unlock: 10/10I hope this will help full"]
['amazing battery life']
['Very nice and fantastic phn, the best smart phn till date, awesome camera good battery life']
['Crisp picture quality, impactful sound and an impressive battery life makes it a worthy investment']
['Battery life is best among all one plus phones']
[' Battery life is decent']
[' Battery life is comparably good, you get around 6 hrs of SOT from a full charge']
[', battery life is awesome it lasted about 14 hours wit

In [4]:
# Picture Quality

picture_quality_desc_list=[]
picture_quality_sentiment_list=[]
rating=['positive','critical']
for rate in rating:
    print(rate)
    review_list=[]
    
    for i in range(1,4):
        reviews_url = 'https://www.amazon.in/OnePlus-Midnight-Black-128GB-Storage/product-reviews/B07DJHY82F/ref=cm_cr_arp_d_viewopt_kywd?ie=UTF8&reviewerType=all_reviews&sortBy=helpful&pageNumber='+str(i)+'&filterByStar='+rate+'&filterByKeyword=Camera'
        page2 = requests.get(reviews_url)
        soup2 = BeautifulSoup(page2.text, 'html.parser')
        title = soup2.find_all(attrs={"data-hook":"review-title"})
        review = soup2.find_all(attrs={"class":"a-size-base review-text review-text-content"})
        for r in range(len(review)):
            desc=[]
            review_list.append(clean(title[r]))
            review_sentences = str(clean(review[r])).split('.')
            for sentence in review_sentences:
                if "Camera" in sentence or "camera" in sentence:
                    desc.append(sentence)
            picture_quality_desc_list.append(desc)
        for i in range(len(picture_quality_desc_list)):
            
            if(rate=="positive"):
                picture_quality_sentiment_list.append([picture_quality_desc_list[i],1])
            elif(rate=="critical"):
                picture_quality_sentiment_list.append([picture_quality_desc_list[i],0])
            
    for x in range(len(review_list)-2):
        print(picture_quality_desc_list[x])
        print('-------------------------')

positive
["Pros:Great battery lifeAmazing performancePremium designImpressive rear and front cameraIn display fingerprint scanner is really fastCons:No headphone jack but you'll get a converterNo notification LEDNo microSD card slotI will give points on my personal experience of 2 days full usage as below:Weight: 9/10OS: 10/10Screen size: 10/10CPU: 10/10Performance: 10/10Storage: 10/10 (you'll get approx 113 gb for use)Battery: 8/10Rear camera: 10/10Front camera: 10/10In display fingerprint scanner: 9/10Face unlock: 10/10I hope this will help full"]
-------------------------
['low light performance of the camera is outstanding']
-------------------------
['Camera - The night mode really captures amazing pictures and the portrait mode is just amazing']
-------------------------
[' :)Excellent battery,Great screen,Amazing performance,Smoooth OS,Great camera,Surprisingly decent audio,Cool screen unlock and ridiculously fast face unlock']
-------------------------
['Issue with the Camera S

In [5]:
# Value for Money

money_desc_list=[]
money_sentiment_list=[]
for rate in rating:
    print(rate)
    review_list=[]
    
    for i in range(1,4):
        reviews_url = 'https://www.amazon.in/OnePlus-Midnight-Black-128GB-Storage/product-reviews/B07DJHY82F/ref=cm_cr_arp_d_viewopt_kywd?ie=UTF8&reviewerType=all_reviews&sortBy=helpful&pageNumber='+str(i)+'&filterByStar='+rate+'&filterByKeyword=Money'
        page2 = requests.get(reviews_url)
        soup2 = BeautifulSoup(page2.text, 'html.parser')
        title = soup2.find_all(attrs={"data-hook":"review-title"})
        review = soup2.find_all(attrs={"class":"a-size-base review-text review-text-content"})
        for r in range(len(review)):
            desc=[]
            review_list.append(clean(title[r]))
            review_sentences = str(clean(review[r])).split('.')
            for sentence in review_sentences:
                if "Money" in sentence or "money" in sentence:
                    desc.append(sentence)
            money_desc_list.append(desc)
            
        for i in range(len(money_desc_list)):
            
            if(rate=="positive"):
                money_sentiment_list.append([money_desc_list[i],1])
            elif(rate=="critical"):
                money_sentiment_list.append([money_desc_list[i],0])
        
    for x in range(len(review_list)-2):
        #print(review_list[x+2])
        print(money_desc_list[x])
        print('-------------------------')

positive
[]
-------------------------
['value for money']
-------------------------
[' But if you already have the OnePlus 6 then don’t waste your money because OnePlus 6 will get all the software feature via OTA updates']
-------------------------
[]
-------------------------
[]
-------------------------
["Best phone !!!In love with the fingerprint scanner and it's animation !Battery lasts one day !Industry leading camera with studio mode works fantastic !Catchy display !Fast like a flash !Great Value for money !!!!!"]
-------------------------
[]
-------------------------
['For the cost , this is one value for money product']
-------------------------
[]
-------------------------
[' Lets hope they keep it as Value for money', 'But overall its a good package and still its a Value for money! You can go for it for sure']
-------------------------
[]
-------------------------
[" At this price range it's a great value for money"]
-------------------------
['A great brand to look forward t

In [6]:
# Sound Quality

sound_quality_desc_list=[]
sound_quality_sentiment_list=[]
for rate in rating:
    print(rate)
    review_list=[]
    
    for i in range(1,4):
        reviews_url = 'https://www.amazon.in/OnePlus-Midnight-Black-128GB-Storage/product-reviews/B07DJHY82F/ref=cm_cr_arp_d_viewopt_kywd?ie=UTF8&reviewerType=all_reviews&sortBy=helpful&pageNumber='+str(i)+'&filterByStar='+rate+'&filterByKeyword=Camera'
        page2 = requests.get(reviews_url)
        soup2 = BeautifulSoup(page2.text, 'html.parser')
        title = soup2.find_all(attrs={"data-hook":"review-title"})
        review = soup2.find_all(attrs={"class":"a-size-base review-text review-text-content"})
        for r in range(len(review)):
            desc=[]
            review_list.append(clean(title[r]))
            review_sentences = str(clean(review[r])).split('.')
            for sentence in review_sentences:
                #print(sentence)
                if "Sound" in sentence or "sound" in sentence:
                    desc.append(sentence)
            sound_quality_desc_list.append(desc)
            
        for i in range(len(sound_quality_desc_list)):
            
            if(rate=="positive"):
                sound_quality_sentiment_list.append([sound_quality_desc_list[i],1])
            elif(rate=="critical"):
                sound_quality_sentiment_list.append([sound_quality_desc_list[i],0])
        
    for x in range(len(review_list)-2):
        #print(review_list[x+2])
        print(sound_quality_desc_list[x])
        print('-------------------------')

positive
[]
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
['Issue with the Camera Slow Motion Mode is Not Working in Home Black Shade is Moving from left to right Sound Quality is not that good']
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
['5 mm / whatever) is ABOVE AVERAGE, but should have been better with greater bass and more fuller ambient sound like LG G7 ThinQ etc']
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
['Sound: Probably the only change I would make']
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
[]
-------------------------
['5) Sound quality is good']
-------------------------
[]
-------------------------
[' For headph

In [7]:
#fingerprint

fingerprint_desc_list=[]
fingerprint_sentiment_list=[]
rating=['positive','critical']
for rate in rating:
    print(rate)
    review_list=[]
    
    for i in range(1,4):
        reviews_url = 'https://www.amazon.in/OnePlus-Midnight-Black-128GB-Storage/product-reviews/B07DJHY82F/ref=cm_cr_arp_d_viewopt_kywd?ie=UTF8&reviewerType=all_reviews&sortBy=helpful&pageNumber='+str(i)+'&filterByStar='+rate+'&filterByKeyword=Fingerprint'
        page2 = requests.get(reviews_url)
        soup2 = BeautifulSoup(page2.text, 'html.parser')
        title = soup2.find_all(attrs={"data-hook":"review-title"})
        review = soup2.find_all(attrs={"class":"a-size-base review-text review-text-content"})
        for r in range(len(review)):
            desc=[]
            review_list.append(clean(title[r]))
            review_sentences = str(clean(review[r])).split('.')
            for sentence in review_sentences:
                if "Fingerprint" in sentence or "fingerprint" in sentence:
                    desc.append(sentence)
            fingerprint_desc_list.append(desc)
            
        for i in range(len(fingerprint_desc_list)):
            if(rate=="positive"):
                fingerprint_sentiment_list.append([fingerprint_desc_list[i],1])
            elif(rate=="critical"):
                fingerprint_sentiment_list.append([fingerprint_desc_list[i],0])
        
    for x in range(len(review_list)-2):
        #print(review_list[x+2])
        
        print(fingerprint_desc_list[x])
        
    

positive
["Pros:Great battery lifeAmazing performancePremium designImpressive rear and front cameraIn display fingerprint scanner is really fastCons:No headphone jack but you'll get a converterNo notification LEDNo microSD card slotI will give points on my personal experience of 2 days full usage as below:Weight: 9/10OS: 10/10Screen size: 10/10CPU: 10/10Performance: 10/10Storage: 10/10 (you'll get approx 113 gb for use)Battery: 8/10Rear camera: 10/10Front camera: 10/10In display fingerprint scanner: 9/10Face unlock: 10/10I hope this will help full"]
['in display fingerprint sensor &amp; face recognition both are good']
[' Fingerprint unlock is also good, if you have face unlock ON then all the time it will unlock with face data before the the fingerprint works']
['The main highlight it has the in-display fingerprint sensor and this is one of the fastest in-display fingerprint sensors']
['Fingerprint sensor, face unlock are exciting features but not indispensible']
[' The in screen fing

In [8]:
master_list = []
for i in range(len(battery_life_desc_list)):
    if battery_life_desc_list[i]:
        master_list.append([battery_life_desc_list[i][0],0])
    
for i in range(len(picture_quality_desc_list)):
    if picture_quality_desc_list[i]:
        master_list.append([picture_quality_desc_list[i][0],1])

for i in range(len(money_desc_list)):
    if money_desc_list[i]:
        master_list.append([money_desc_list[i][0],2])

for i in range(len(sound_quality_desc_list)):
    if sound_quality_desc_list[i]:
        master_list.append([sound_quality_desc_list[i][0],3])
    
for i in range(len(fingerprint_desc_list)):
    if fingerprint_desc_list[i]:
        master_list.append([fingerprint_desc_list[i][0],4])

In [9]:
import random
shuffled_master_list=master_list
random.shuffle(shuffled_master_list)
random.shuffle(battery_life_sentiment_list)
random.shuffle(picture_quality_sentiment_list)
random.shuffle(money_sentiment_list)
random.shuffle(sound_quality_sentiment_list)
random.shuffle(fingerprint_sentiment_list)

In [47]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


def preprocessing_text(text_to_process):
    list_to_return=[]
    for i in range(0,len(text_to_process)):
        # column : "Review", row ith 
        #print(i)
        if not text_to_process[i]:
            del text_to_process[i]
        #print(fingerprint_set[i][0][0])
        review = re.sub('[^a-zA-Z]', ' ', str(text_to_process[i][0]))  

        # convert all cases to lower cases 
        review = review.lower()  

        # split to array(default delimiter is " ") 
        review = review.split()  

        # creating PorterStemmer object to 
        # take main stem of each word 
        ps = PorterStemmer()  

        # loop for stemming each word 
        # in string array at ith row     
        review = [ps.stem(word) for word in review 
                    if not word in set(stopwords.words('english'))]  

        # rejoin all string array elements 
        # to create back into a string 
        review = ' '.join(review)   

        # append each string to create 
        # array of clean text  
        list_to_return.append(review)
    return list_to_return
    


[nltk_data] Downloading package stopwords to /home/bhumil/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [48]:
from sklearn.feature_extraction.text import CountVectorizer
processted_master_list = preprocessing_text(shuffled_master_list)
cv_new=CountVectorizer()
X_new=cv_new.fit_transform(processted_master_list).toarray()

In [49]:
y_new=[]
for i in range(0,len(shuffled_master_list)):
    y_new.append(shuffled_master_list[i][1])
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new,np.asarray(y_new),test_size=0.2)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=501, criterion='entropy')
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=501, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [50]:
y_pred=model.predict(X_test)
print(y_pred)

[3 0 1 3 1 2 2 0 0 0 4 0 1 0 2 1 0 1 4 4 0 4 1 0 4 4 2 4 4 0 1 2 4 1 4 4 0
 2 1 2 0 4 4 2 4]


In [51]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,y_test))

[[11  0  0  0  1]
 [ 1  8  1  1  2]
 [ 0  0  7  0  0]
 [ 0  0  0  1  0]
 [ 0  1  0  0 11]]
0.8444444444444444


In [52]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

def classification_model(operation_perform,list_to_train):
    cvi=CountVectorizer()
    X_i=cvi.fit_transform(operation_perform).toarray()
    y_new_i=[]
    for i in range(0,len(list_to_train)):
        y_new_i.append(list_to_train[i][1])
    print(len(X_i))
    print(len(y_new_i))
    X_train, X_test, y_train, y_test = train_test_split(X_i,np.asarray(y_new_i),test_size=0.2)
    model=RandomForestClassifier(n_estimators=501, criterion='entropy')
    model.fit(X_train,y_train)
    
    model_pred=model.predict(X_test)
    cm=confusion_matrix(y_test,model_pred)
    print(cm)
    print(accuracy_score(model_pred,y_test))

In [53]:
corpus_battery = preprocessing_text(battery_life_sentiment_list)
battery_model = classification_model(corpus_battery,battery_life_sentiment_list)

corpus_picture_quality = preprocessing_text(picture_quality_sentiment_list)
picture_quality_model = classification_model(corpus_picture_quality,picture_quality_sentiment_list)

corpus_money = preprocessing_text(money_sentiment_list)
money_model = classification_model(corpus_money,money_sentiment_list)

corpus_sound_quality = preprocessing_text(sound_quality_sentiment_list)
sound_quality_model = classification_model(corpus_sound_quality,sound_quality_sentiment_list)

corpus_fingerprint = preprocessing_text(fingerprint_sentiment_list)
fingerprint_model = classification_model(corpus_fingerprint,fingerprint_sentiment_list)

210
210
[[25  6]
 [10  1]]
0.6190476190476191
210
210
[[16 11]
 [12  3]]
0.4523809523809524
180
180
[[19  2]
 [15  0]]
0.5277777777777778
210
210
[[32  0]
 [10  0]]
0.7619047619047619
210
210
[[21 13]
 [ 7  1]]
0.5238095238095238


In [54]:

#most recent 100 reviews
# import pymongo
# myclient = pymongo.MongoClient("mongodb://localhost:27017/")
# mydb = myclient["course5i"]
# mycol = mydb["oneplus 6t"]
# product_id = mycol.insert_one({"Reviews":reviewdict})
# mycol.insert_many(mylist)

master_review_list=[]
short_review_description_list=[]
mylist=[]

for i in range(1,30):
    if len(master_review_list)<100:
        most_recent = 'https://www.amazon.in/OnePlus-Midnight-Black-256GB-Storage/product-reviews/B07DJCJBRD/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber='+str(i)
        page3 = requests.get(most_recent)
        soup3 = BeautifulSoup(page3.text, 'html.parser')
        most_recent_reviews = soup3.find_all(attrs={"class":"a-size-base review-text review-text-content"})
        for mrr in most_recent_reviews:
            master_review_list.append(clean(mrr))
            list_of_sentences = str(clean(mrr)).split('.')
            temp = ""
            for sentence in list_of_sentences:
                if "Battery" in sentence or "battery" in sentence or "Picture" in sentence or "picture" in sentence or "camera" in sentence or "Camera" in sentence or "Money" in sentence or "money" in sentence or "Sound" in sentence or "sound" in sentence or "Fingerprint" in sentence or "fingerprint" in sentence:
                    temp+=sentence
            if len(temp)==0:
                short_review_description_list.append(clean(mrr))
            else:
                short_review_description_list.append(temp)
                

In [68]:

def preprocess_for_prediction(list_to_predict):
corpus_new2 = []
    for i in range(0,len(short_review_description_list)):
        # column : "Review", row ith 
        #print(i)
        if not short_review_description_list[i]:
            del short_review_description_list[i]
        #print(fingerprint_set[i][0][0])
        review2 = re.sub('[^a-zA-Z]', ' ', str(short_review_description_list[i]))  

        # convert all cases to lower cases 
        review2 = review2.lower()  

        # split to array(default delimiter is " ") 
        review2 = review2.split()  

        # creating PorterStemmer object to 
        # take main stem of each word 
        ps2 = PorterStemmer()  

        # loop for stemming each word 
        # in string array at ith row     
        review2 = [ps2.stem(word) for word in review2 
                    if not word in set(stopwords.words('english'))]  

        # rejoin all string array elements 
        # to create back into a string 
        review2 = ' '.join(review2)   

        # append each string to create 
        # array of clean text  
        corpus_new2.append(review2)
        cv2=CountVectorizer()
        X_new_corpus2=cv2.fit_transform(corpus_new2).toarray()
    return X_new_corpus
    
x_train = preprocess_for_prediction(short_review_description_list)
predicted_classification = model.predict(x_train)
print(predicted_classification)
for p in predicted_classification:
    if predicted_classification==0:
        print(battery_model.predict(x_train))
    if predicted_classification==1:
        print(picture_quality_model.predict(x_train))
    if predicted_classification==2:
        print(money_model.predict(x_train))
    if predicted_classification==3:
        print(sound_quality_model.predict(x_train))
    if predicted_classification==4:
        print(fingerprint_model.predict(x_train))
        
